create table friendship (id bigint not null auto_increment, status varchar(20), user_receiver_id bigint, user_sender_id bigint, primary key (id)) engine=InnoDB;
create table friendship_status (id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table likes (id bigint not null auto_increment, user_id bigint, user_post_id bigint, primary key (id)) engine=InnoDB;
create table movie (id integer not null, director varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table skills (id bigint not null auto_increment, tag_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, company_name varchar(255), description varchar(255), finished_at_month varchar(255), finished_at_year varchar(255), first_name varchar(255), last_name varchar(255), started_at_month varchar(255), started_at_year varchar(255), last_title varchar(255), username varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table userpost (id bigint not null auto_increment, content varchar(255), created_date datetime(6), file varchar(255), media varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, avatar varchar(255), email varchar(255) not null, email_verified bit not null, is_active bit, image_url varchar(255), is_company bit, name varchar(255) not null, password varchar(255), provider varchar(255) not null, provider_id varchar(255), username varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK9551piq2wp9kh4kket0wr65vt unique (username);
alter table user_profile add constraint UK_ebc21hy5j7scdvcjt0jy6xxrv unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_m6rqhr1nq3b6j8aglc4tlhaj6 unique (user_profile_id);
alter table friendship add constraint FKl3fmi2qvg60ic6kfaatp5fbci foreign key (user_receiver_id) references users (id);
alter table friendship add constraint FKgb2wm94b4p97ir8ghl18raqfs foreign key (user_sender_id) references users (id);
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users (id);
alter table likes add constraint FKqdo6v41e0f5uv4opn66n61wbe foreign key (user_post_id) references userpost (id);
alter table skills add constraint FK5fl0vpj28i7audg87u2322vn5 foreign key (tag_id) references tag (id);
alter table skills add constraint FKo8dhr4cqp5nowj5o9km5fjhaq foreign key (user_id) references users (id);
alter table user_profile add constraint FKuganfwvnbll4kn2a3jeyxtyi foreign key (user_id) references users (id);
alter table userpost add constraint FKnjhvkcvrsm7vksyjb7eljn2uw foreign key (user_profile_id) references user_profile (id);
alter table users add constraint FKgvxffhxghiogrd4g2sqompabh foreign key (user_profile_id) references user_profile (id);
create table friendship (id bigint not null auto_increment, status varchar(20), user_receiver_id bigint, user_sender_id bigint, primary key (id)) engine=InnoDB;
create table friendship_status (id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table likes (id bigint not null auto_increment, user_id bigint, user_post_id bigint, primary key (id)) engine=InnoDB;
create table movie (id integer not null, director varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table skills (id bigint not null auto_increment, tag_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, company_name varchar(255), description varchar(255), finished_at_month varchar(255), finished_at_year varchar(255), first_name varchar(255), last_name varchar(255), started_at_month varchar(255), started_at_year varchar(255), last_title varchar(255), username varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table userpost (id bigint not null auto_increment, content varchar(255), created_date datetime(6), file varchar(255), media varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, avatar varchar(255), email varchar(255) not null, email_verified bit not null, is_active bit, image_url varchar(255), is_company bit, name varchar(255) not null, password varchar(255), provider varchar(255) not null, provider_id varchar(255), username varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK9551piq2wp9kh4kket0wr65vt unique (username);
alter table user_profile add constraint UK_ebc21hy5j7scdvcjt0jy6xxrv unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_m6rqhr1nq3b6j8aglc4tlhaj6 unique (user_profile_id);
alter table friendship add constraint FKl3fmi2qvg60ic6kfaatp5fbci foreign key (user_receiver_id) references users (id);
alter table friendship add constraint FKgb2wm94b4p97ir8ghl18raqfs foreign key (user_sender_id) references users (id);
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users (id);
alter table likes add constraint FKqdo6v41e0f5uv4opn66n61wbe foreign key (user_post_id) references userpost (id);
alter table skills add constraint FK5fl0vpj28i7audg87u2322vn5 foreign key (tag_id) references tag (id);
alter table skills add constraint FKo8dhr4cqp5nowj5o9km5fjhaq foreign key (user_id) references users (id);
alter table user_profile add constraint FKuganfwvnbll4kn2a3jeyxtyi foreign key (user_id) references users (id);
alter table userpost add constraint FKnjhvkcvrsm7vksyjb7eljn2uw foreign key (user_profile_id) references user_profile (id);
alter table users add constraint FKgvxffhxghiogrd4g2sqompabh foreign key (user_profile_id) references user_profile (id);
create table friendship (id bigint not null auto_increment, status varchar(20), user_receiver_id bigint, user_sender_id bigint, primary key (id)) engine=InnoDB;
create table friendship_status (id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table likes (id bigint not null auto_increment, user_id bigint, user_post_id bigint, primary key (id)) engine=InnoDB;
create table movie (id integer not null, director varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table skills (id bigint not null auto_increment, tag_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, company_name varchar(255), description varchar(255), finished_at_month varchar(255), finished_at_year varchar(255), first_name varchar(255), last_name varchar(255), started_at_month varchar(255), started_at_year varchar(255), last_title varchar(255), username varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table userpost (id bigint not null auto_increment, content varchar(255), created_date datetime(6), file varchar(255), media varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, avatar varchar(255), email varchar(255) not null, email_verified bit not null, is_active bit, image_url varchar(255), is_company bit, name varchar(255) not null, password varchar(255), provider varchar(255) not null, provider_id varchar(255), username varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK9551piq2wp9kh4kket0wr65vt unique (username);
alter table user_profile add constraint UK_ebc21hy5j7scdvcjt0jy6xxrv unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_m6rqhr1nq3b6j8aglc4tlhaj6 unique (user_profile_id);
alter table friendship add constraint FKl3fmi2qvg60ic6kfaatp5fbci foreign key (user_receiver_id) references users (id);
alter table friendship add constraint FKgb2wm94b4p97ir8ghl18raqfs foreign key (user_sender_id) references users (id);
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users (id);
alter table likes add constraint FKqdo6v41e0f5uv4opn66n61wbe foreign key (user_post_id) references userpost (id);
alter table skills add constraint FK5fl0vpj28i7audg87u2322vn5 foreign key (tag_id) references tag (id);
alter table skills add constraint FKo8dhr4cqp5nowj5o9km5fjhaq foreign key (user_id) references users (id);
alter table user_profile add constraint FKuganfwvnbll4kn2a3jeyxtyi foreign key (user_id) references users (id);
alter table userpost add constraint FKnjhvkcvrsm7vksyjb7eljn2uw foreign key (user_profile_id) references user_profile (id);
alter table users add constraint FKgvxffhxghiogrd4g2sqompabh foreign key (user_profile_id) references user_profile (id);
create table friendship (id bigint not null auto_increment, status varchar(20), user_receiver_id bigint, user_sender_id bigint, primary key (id)) engine=InnoDB;
create table friendship_status (id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table likes (id bigint not null auto_increment, user_id bigint, user_post_id bigint, primary key (id)) engine=InnoDB;
create table movie (id integer not null, director varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table skills (id bigint not null auto_increment, tag_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, company_name varchar(255), description varchar(255), finished_at_month varchar(255), finished_at_year varchar(255), first_name varchar(255), last_name varchar(255), started_at_month varchar(255), started_at_year varchar(255), last_title varchar(255), username varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table userpost (id bigint not null auto_increment, content varchar(255), created_date datetime(6), file varchar(255), media varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, avatar varchar(255), email varchar(255) not null, email_verified bit not null, is_active bit, image_url varchar(255), is_company bit, name varchar(255) not null, password varchar(255), provider varchar(255) not null, provider_id varchar(255), username varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK9551piq2wp9kh4kket0wr65vt unique (username);
alter table user_profile add constraint UK_ebc21hy5j7scdvcjt0jy6xxrv unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_m6rqhr1nq3b6j8aglc4tlhaj6 unique (user_profile_id);
alter table friendship add constraint FKl3fmi2qvg60ic6kfaatp5fbci foreign key (user_receiver_id) references users (id);
alter table friendship add constraint FKgb2wm94b4p97ir8ghl18raqfs foreign key (user_sender_id) references users (id);
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users (id);
alter table likes add constraint FKqdo6v41e0f5uv4opn66n61wbe foreign key (user_post_id) references userpost (id);
alter table skills add constraint FK5fl0vpj28i7audg87u2322vn5 foreign key (tag_id) references tag (id);
alter table skills add constraint FKo8dhr4cqp5nowj5o9km5fjhaq foreign key (user_id) references users (id);
alter table user_profile add constraint FKuganfwvnbll4kn2a3jeyxtyi foreign key (user_id) references users (id);
alter table userpost add constraint FKnjhvkcvrsm7vksyjb7eljn2uw foreign key (user_profile_id) references user_profile (id);
alter table users add constraint FKgvxffhxghiogrd4g2sqompabh foreign key (user_profile_id) references user_profile (id);
create table friendship (id bigint not null auto_increment, status varchar(20), user_receiver_id bigint, user_sender_id bigint, primary key (id)) engine=InnoDB;
create table friendship_status (id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table likes (id bigint not null auto_increment, user_id bigint, user_post_id bigint, primary key (id)) engine=InnoDB;
create table movie (id integer not null, director varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table skills (id bigint not null auto_increment, tag_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, company_name varchar(255), description varchar(255), finished_at_month varchar(255), finished_at_year varchar(255), first_name varchar(255), last_name varchar(255), started_at_month varchar(255), started_at_year varchar(255), last_title varchar(255), username varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table userpost (id bigint not null auto_increment, content varchar(255), created_date datetime(6), file varchar(255), media varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, avatar varchar(255), email varchar(255) not null, email_verified bit not null, is_active bit, image_url varchar(255), is_company bit, name varchar(255) not null, password varchar(255), provider varchar(255) not null, provider_id varchar(255), username varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK9551piq2wp9kh4kket0wr65vt unique (username);
alter table user_profile add constraint UK_ebc21hy5j7scdvcjt0jy6xxrv unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_m6rqhr1nq3b6j8aglc4tlhaj6 unique (user_profile_id);
alter table friendship add constraint FKl3fmi2qvg60ic6kfaatp5fbci foreign key (user_receiver_id) references users (id);
alter table friendship add constraint FKgb2wm94b4p97ir8ghl18raqfs foreign key (user_sender_id) references users (id);
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users (id);
alter table likes add constraint FKqdo6v41e0f5uv4opn66n61wbe foreign key (user_post_id) references userpost (id);
alter table skills add constraint FK5fl0vpj28i7audg87u2322vn5 foreign key (tag_id) references tag (id);
alter table skills add constraint FKo8dhr4cqp5nowj5o9km5fjhaq foreign key (user_id) references users (id);
alter table user_profile add constraint FKuganfwvnbll4kn2a3jeyxtyi foreign key (user_id) references users (id);
alter table userpost add constraint FKnjhvkcvrsm7vksyjb7eljn2uw foreign key (user_profile_id) references user_profile (id);
alter table users add constraint FKgvxffhxghiogrd4g2sqompabh foreign key (user_profile_id) references user_profile (id);
create table friendship (id bigint not null auto_increment, status varchar(20), user_receiver_id bigint, user_sender_id bigint, primary key (id)) engine=InnoDB;
create table friendship_status (id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table likes (id bigint not null auto_increment, user_id bigint, user_post_id bigint, primary key (id)) engine=InnoDB;
create table movie (id integer not null, director varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table skills (id bigint not null auto_increment, tag_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, company_name varchar(255), description varchar(255), finished_at_month varchar(255), finished_at_year varchar(255), first_name varchar(255), last_name varchar(255), started_at_month varchar(255), started_at_year varchar(255), last_title varchar(255), username varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table userpost (id bigint not null auto_increment, content varchar(255), created_date datetime(6), file varchar(255), media varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, avatar varchar(255), email varchar(255) not null, email_verified bit not null, is_active bit, image_url varchar(255), is_company bit, name varchar(255) not null, password varchar(255), provider varchar(255) not null, provider_id varchar(255), username varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK9551piq2wp9kh4kket0wr65vt unique (username);
alter table user_profile add constraint UK_ebc21hy5j7scdvcjt0jy6xxrv unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_m6rqhr1nq3b6j8aglc4tlhaj6 unique (user_profile_id);
alter table friendship add constraint FKl3fmi2qvg60ic6kfaatp5fbci foreign key (user_receiver_id) references users (id);
alter table friendship add constraint FKgb2wm94b4p97ir8ghl18raqfs foreign key (user_sender_id) references users (id);
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users (id);
alter table likes add constraint FKqdo6v41e0f5uv4opn66n61wbe foreign key (user_post_id) references userpost (id);
alter table skills add constraint FK5fl0vpj28i7audg87u2322vn5 foreign key (tag_id) references tag (id);
alter table skills add constraint FKo8dhr4cqp5nowj5o9km5fjhaq foreign key (user_id) references users (id);
alter table user_profile add constraint FKuganfwvnbll4kn2a3jeyxtyi foreign key (user_id) references users (id);
alter table userpost add constraint FKnjhvkcvrsm7vksyjb7eljn2uw foreign key (user_profile_id) references user_profile (id);
alter table users add constraint FKgvxffhxghiogrd4g2sqompabh foreign key (user_profile_id) references user_profile (id);
create table friendship (id bigint not null auto_increment, status varchar(20), user_receiver_id bigint, user_sender_id bigint, primary key (id)) engine=InnoDB;
create table friendship_status (id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table likes (id bigint not null auto_increment, user_id bigint, user_post_id bigint, primary key (id)) engine=InnoDB;
create table movie (id integer not null, director varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table skills (id bigint not null auto_increment, tag_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, company_name varchar(255), description varchar(255), finished_at_month varchar(255), finished_at_year varchar(255), first_name varchar(255), last_name varchar(255), started_at_month varchar(255), started_at_year varchar(255), last_title varchar(255), username varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table userpost (id bigint not null auto_increment, content varchar(255), created_date datetime(6), file varchar(255), media varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, avatar varchar(255), email varchar(255) not null, email_verified bit not null, is_active bit, image_url varchar(255), is_company bit, name varchar(255) not null, password varchar(255), provider varchar(255) not null, provider_id varchar(255), username varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK9551piq2wp9kh4kket0wr65vt unique (username);
alter table user_profile add constraint UK_ebc21hy5j7scdvcjt0jy6xxrv unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_m6rqhr1nq3b6j8aglc4tlhaj6 unique (user_profile_id);
alter table friendship add constraint FKl3fmi2qvg60ic6kfaatp5fbci foreign key (user_receiver_id) references users (id);
alter table friendship add constraint FKgb2wm94b4p97ir8ghl18raqfs foreign key (user_sender_id) references users (id);
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users (id);
alter table likes add constraint FKqdo6v41e0f5uv4opn66n61wbe foreign key (user_post_id) references userpost (id);
alter table skills add constraint FK5fl0vpj28i7audg87u2322vn5 foreign key (tag_id) references tag (id);
alter table skills add constraint FKo8dhr4cqp5nowj5o9km5fjhaq foreign key (user_id) references users (id);
alter table user_profile add constraint FKuganfwvnbll4kn2a3jeyxtyi foreign key (user_id) references users (id);
alter table userpost add constraint FKnjhvkcvrsm7vksyjb7eljn2uw foreign key (user_profile_id) references user_profile (id);
alter table users add constraint FKgvxffhxghiogrd4g2sqompabh foreign key (user_profile_id) references user_profile (id);
create table friendship (id bigint not null auto_increment, status varchar(20), user_receiver_id bigint, user_sender_id bigint, primary key (id)) engine=InnoDB;
create table friendship_status (id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table likes (id bigint not null auto_increment, user_id bigint, user_post_id bigint, primary key (id)) engine=InnoDB;
create table movie (id integer not null, director varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table skills (id bigint not null auto_increment, tag_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, company_name varchar(255), description varchar(255), finished_at_month varchar(255), finished_at_year varchar(255), first_name varchar(255), last_name varchar(255), started_at_month varchar(255), started_at_year varchar(255), last_title varchar(255), username varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table userpost (id bigint not null auto_increment, content varchar(255), created_date datetime(6), file varchar(255), media varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, avatar varchar(255), email varchar(255) not null, email_verified bit not null, is_active bit, image_url varchar(255), is_company bit, name varchar(255) not null, password varchar(255), provider varchar(255) not null, provider_id varchar(255), username varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK9551piq2wp9kh4kket0wr65vt unique (username);
alter table user_profile add constraint UK_ebc21hy5j7scdvcjt0jy6xxrv unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_m6rqhr1nq3b6j8aglc4tlhaj6 unique (user_profile_id);
alter table friendship add constraint FKl3fmi2qvg60ic6kfaatp5fbci foreign key (user_receiver_id) references users (id);
alter table friendship add constraint FKgb2wm94b4p97ir8ghl18raqfs foreign key (user_sender_id) references users (id);
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users (id);
alter table likes add constraint FKqdo6v41e0f5uv4opn66n61wbe foreign key (user_post_id) references userpost (id);
alter table skills add constraint FK5fl0vpj28i7audg87u2322vn5 foreign key (tag_id) references tag (id);
alter table skills add constraint FKo8dhr4cqp5nowj5o9km5fjhaq foreign key (user_id) references users (id);
alter table user_profile add constraint FKuganfwvnbll4kn2a3jeyxtyi foreign key (user_id) references users (id);
alter table userpost add constraint FKnjhvkcvrsm7vksyjb7eljn2uw foreign key (user_profile_id) references user_profile (id);
alter table users add constraint FKgvxffhxghiogrd4g2sqompabh foreign key (user_profile_id) references user_profile (id);
create table friendship (id bigint not null auto_increment, status varchar(20), user_receiver_id bigint, user_sender_id bigint, primary key (id)) engine=InnoDB;
create table friendship_status (id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table likes (id bigint not null auto_increment, user_id bigint, user_post_id bigint, primary key (id)) engine=InnoDB;
create table movie (id integer not null, director varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table skills (id bigint not null auto_increment, tag_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, company_name varchar(255), description varchar(255), finished_at_month varchar(255), finished_at_year varchar(255), first_name varchar(255), last_name varchar(255), started_at_month varchar(255), started_at_year varchar(255), last_title varchar(255), username varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table userpost (id bigint not null auto_increment, content varchar(255), created_date datetime(6), file varchar(255), media varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, avatar varchar(255), email varchar(255) not null, email_verified bit not null, is_active bit, image_url varchar(255), is_company bit, name varchar(255) not null, password varchar(255), provider varchar(255) not null, provider_id varchar(255), username varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK9551piq2wp9kh4kket0wr65vt unique (username);
alter table user_profile add constraint UK_ebc21hy5j7scdvcjt0jy6xxrv unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_m6rqhr1nq3b6j8aglc4tlhaj6 unique (user_profile_id);
alter table friendship add constraint FKl3fmi2qvg60ic6kfaatp5fbci foreign key (user_receiver_id) references users (id);
alter table friendship add constraint FKgb2wm94b4p97ir8ghl18raqfs foreign key (user_sender_id) references users (id);
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users (id);
alter table likes add constraint FKqdo6v41e0f5uv4opn66n61wbe foreign key (user_post_id) references userpost (id);
alter table skills add constraint FK5fl0vpj28i7audg87u2322vn5 foreign key (tag_id) references tag (id);
alter table skills add constraint FKo8dhr4cqp5nowj5o9km5fjhaq foreign key (user_id) references users (id);
alter table user_profile add constraint FKuganfwvnbll4kn2a3jeyxtyi foreign key (user_id) references users (id);
alter table userpost add constraint FKnjhvkcvrsm7vksyjb7eljn2uw foreign key (user_profile_id) references user_profile (id);
alter table users add constraint FKgvxffhxghiogrd4g2sqompabh foreign key (user_profile_id) references user_profile (id);
create table friendship (id bigint not null auto_increment, status varchar(20), user_receiver_id bigint, user_sender_id bigint, primary key (id)) engine=InnoDB;
create table friendship_status (id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table likes (id bigint not null auto_increment, user_id bigint, user_post_id bigint, primary key (id)) engine=InnoDB;
create table movie (id integer not null, director varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table skills (id bigint not null auto_increment, tag_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, company_name varchar(255), description varchar(255), finished_at_month varchar(255), finished_at_year varchar(255), first_name varchar(255), last_name varchar(255), started_at_month varchar(255), started_at_year varchar(255), last_title varchar(255), username varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table userpost (id bigint not null auto_increment, content varchar(255), created_date datetime(6), file varchar(255), media varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, avatar varchar(255), email varchar(255) not null, email_verified bit not null, is_active bit, image_url varchar(255), is_company bit, name varchar(255) not null, password varchar(255), provider varchar(255) not null, provider_id varchar(255), username varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK9551piq2wp9kh4kket0wr65vt unique (username);
alter table user_profile add constraint UK_ebc21hy5j7scdvcjt0jy6xxrv unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_m6rqhr1nq3b6j8aglc4tlhaj6 unique (user_profile_id);
alter table friendship add constraint FKl3fmi2qvg60ic6kfaatp5fbci foreign key (user_receiver_id) references users (id);
alter table friendship add constraint FKgb2wm94b4p97ir8ghl18raqfs foreign key (user_sender_id) references users (id);
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users (id);
alter table likes add constraint FKqdo6v41e0f5uv4opn66n61wbe foreign key (user_post_id) references userpost (id);
alter table skills add constraint FK5fl0vpj28i7audg87u2322vn5 foreign key (tag_id) references tag (id);
alter table skills add constraint FKo8dhr4cqp5nowj5o9km5fjhaq foreign key (user_id) references users (id);
alter table user_profile add constraint FKuganfwvnbll4kn2a3jeyxtyi foreign key (user_id) references users (id);
alter table userpost add constraint FKnjhvkcvrsm7vksyjb7eljn2uw foreign key (user_profile_id) references user_profile (id);
alter table users add constraint FKgvxffhxghiogrd4g2sqompabh foreign key (user_profile_id) references user_profile (id);
create table friendship (id bigint not null auto_increment, status varchar(20), user_receiver_id bigint, user_sender_id bigint, primary key (id)) engine=InnoDB;
create table friendship_status (id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table likes (id bigint not null auto_increment, user_id bigint, user_post_id bigint, primary key (id)) engine=InnoDB;
create table movie (id integer not null, director varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table skills (id bigint not null auto_increment, tag_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, company_name varchar(255), description varchar(255), finished_at_month varchar(255), finished_at_year varchar(255), first_name varchar(255), last_name varchar(255), started_at_month varchar(255), started_at_year varchar(255), last_title varchar(255), username varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table userpost (id bigint not null auto_increment, content varchar(255), created_date datetime(6), file varchar(255), media varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, avatar varchar(255), email varchar(255) not null, email_verified bit not null, is_active bit, image_url varchar(255), is_company bit, name varchar(255) not null, password varchar(255), provider varchar(255) not null, provider_id varchar(255), username varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK9551piq2wp9kh4kket0wr65vt unique (username);
alter table user_profile add constraint UK_ebc21hy5j7scdvcjt0jy6xxrv unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_m6rqhr1nq3b6j8aglc4tlhaj6 unique (user_profile_id);
alter table friendship add constraint FKl3fmi2qvg60ic6kfaatp5fbci foreign key (user_receiver_id) references users (id);
alter table friendship add constraint FKgb2wm94b4p97ir8ghl18raqfs foreign key (user_sender_id) references users (id);
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users (id);
alter table likes add constraint FKqdo6v41e0f5uv4opn66n61wbe foreign key (user_post_id) references userpost (id);
alter table skills add constraint FK5fl0vpj28i7audg87u2322vn5 foreign key (tag_id) references tag (id);
alter table skills add constraint FKo8dhr4cqp5nowj5o9km5fjhaq foreign key (user_id) references users (id);
alter table user_profile add constraint FKuganfwvnbll4kn2a3jeyxtyi foreign key (user_id) references users (id);
alter table userpost add constraint FKnjhvkcvrsm7vksyjb7eljn2uw foreign key (user_profile_id) references user_profile (id);
alter table users add constraint FKgvxffhxghiogrd4g2sqompabh foreign key (user_profile_id) references user_profile (id);
create table friendship (id bigint not null auto_increment, status varchar(20), user_receiver_id bigint, user_sender_id bigint, primary key (id)) engine=InnoDB;
create table friendship_status (id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table likes (id bigint not null auto_increment, user_id bigint, user_post_id bigint, primary key (id)) engine=InnoDB;
create table movie (id integer not null, director varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table skills (id bigint not null auto_increment, tag_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, company_name varchar(255), description varchar(255), finished_at_month varchar(255), finished_at_year varchar(255), first_name varchar(255), last_name varchar(255), started_at_month varchar(255), started_at_year varchar(255), last_title varchar(255), username varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table userpost (id bigint not null auto_increment, content varchar(255), created_date datetime(6), file varchar(255), media varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, avatar varchar(255), email varchar(255) not null, email_verified bit not null, is_active bit, image_url varchar(255), is_company bit, name varchar(255) not null, password varchar(255), provider varchar(255) not null, provider_id varchar(255), username varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK9551piq2wp9kh4kket0wr65vt unique (username);
alter table user_profile add constraint UK_ebc21hy5j7scdvcjt0jy6xxrv unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_m6rqhr1nq3b6j8aglc4tlhaj6 unique (user_profile_id);
alter table friendship add constraint FKl3fmi2qvg60ic6kfaatp5fbci foreign key (user_receiver_id) references users (id);
alter table friendship add constraint FKgb2wm94b4p97ir8ghl18raqfs foreign key (user_sender_id) references users (id);
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users (id);
alter table likes add constraint FKqdo6v41e0f5uv4opn66n61wbe foreign key (user_post_id) references userpost (id);
alter table skills add constraint FK5fl0vpj28i7audg87u2322vn5 foreign key (tag_id) references tag (id);
alter table skills add constraint FKo8dhr4cqp5nowj5o9km5fjhaq foreign key (user_id) references users (id);
alter table user_profile add constraint FKuganfwvnbll4kn2a3jeyxtyi foreign key (user_id) references users (id);
alter table userpost add constraint FKnjhvkcvrsm7vksyjb7eljn2uw foreign key (user_profile_id) references user_profile (id);
alter table users add constraint FKgvxffhxghiogrd4g2sqompabh foreign key (user_profile_id) references user_profile (id);
create table friendship (id bigint not null auto_increment, status varchar(20), user_receiver_id bigint, user_sender_id bigint, primary key (id)) engine=InnoDB;
create table friendship_status (id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table likes (id bigint not null auto_increment, user_id bigint, user_post_id bigint, primary key (id)) engine=InnoDB;
create table movie (id integer not null, director varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table skills (id bigint not null auto_increment, tag_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, company_name varchar(255), description varchar(255), finished_at_month varchar(255), finished_at_year varchar(255), first_name varchar(255), last_name varchar(255), started_at_month varchar(255), started_at_year varchar(255), last_title varchar(255), username varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table userpost (id bigint not null auto_increment, content varchar(255), created_date datetime(6), file varchar(255), media varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, avatar varchar(255), email varchar(255) not null, email_verified bit not null, is_active bit, image_url varchar(255), is_company bit, name varchar(255) not null, password varchar(255), provider varchar(255) not null, provider_id varchar(255), username varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK9551piq2wp9kh4kket0wr65vt unique (username);
alter table user_profile add constraint UK_ebc21hy5j7scdvcjt0jy6xxrv unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_m6rqhr1nq3b6j8aglc4tlhaj6 unique (user_profile_id);
alter table friendship add constraint FKl3fmi2qvg60ic6kfaatp5fbci foreign key (user_receiver_id) references users (id);
alter table friendship add constraint FKgb2wm94b4p97ir8ghl18raqfs foreign key (user_sender_id) references users (id);
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users (id);
alter table likes add constraint FKqdo6v41e0f5uv4opn66n61wbe foreign key (user_post_id) references userpost (id);
alter table skills add constraint FK5fl0vpj28i7audg87u2322vn5 foreign key (tag_id) references tag (id);
alter table skills add constraint FKo8dhr4cqp5nowj5o9km5fjhaq foreign key (user_id) references users (id);
alter table user_profile add constraint FKuganfwvnbll4kn2a3jeyxtyi foreign key (user_id) references users (id);
alter table userpost add constraint FKnjhvkcvrsm7vksyjb7eljn2uw foreign key (user_profile_id) references user_profile (id);
alter table users add constraint FKgvxffhxghiogrd4g2sqompabh foreign key (user_profile_id) references user_profile (id);
create table friendship (id bigint not null auto_increment, status varchar(20), user_receiver_id bigint, user_sender_id bigint, primary key (id)) engine=InnoDB;
create table friendship_status (id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table likes (id bigint not null auto_increment, user_id bigint, user_post_id bigint, primary key (id)) engine=InnoDB;
create table movie (id integer not null, director varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table skills (id bigint not null auto_increment, tag_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, company_name varchar(255), description varchar(255), finished_at_month varchar(255), finished_at_year varchar(255), first_name varchar(255), last_name varchar(255), started_at_month varchar(255), started_at_year varchar(255), last_title varchar(255), username varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table userpost (id bigint not null auto_increment, content varchar(255), created_date datetime(6), file varchar(255), media varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, avatar varchar(255), email varchar(255) not null, email_verified bit not null, is_active bit, image_url varchar(255), is_company bit, name varchar(255) not null, password varchar(255), provider varchar(255) not null, provider_id varchar(255), username varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK9551piq2wp9kh4kket0wr65vt unique (username);
alter table user_profile add constraint UK_ebc21hy5j7scdvcjt0jy6xxrv unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_m6rqhr1nq3b6j8aglc4tlhaj6 unique (user_profile_id);
alter table friendship add constraint FKl3fmi2qvg60ic6kfaatp5fbci foreign key (user_receiver_id) references users (id);
alter table friendship add constraint FKgb2wm94b4p97ir8ghl18raqfs foreign key (user_sender_id) references users (id);
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users (id);
alter table likes add constraint FKqdo6v41e0f5uv4opn66n61wbe foreign key (user_post_id) references userpost (id);
alter table skills add constraint FK5fl0vpj28i7audg87u2322vn5 foreign key (tag_id) references tag (id);
alter table skills add constraint FKo8dhr4cqp5nowj5o9km5fjhaq foreign key (user_id) references users (id);
alter table user_profile add constraint FKuganfwvnbll4kn2a3jeyxtyi foreign key (user_id) references users (id);
alter table userpost add constraint FKnjhvkcvrsm7vksyjb7eljn2uw foreign key (user_profile_id) references user_profile (id);
alter table users add constraint FKgvxffhxghiogrd4g2sqompabh foreign key (user_profile_id) references user_profile (id);
create table friendship (id bigint not null auto_increment, status varchar(20), user_receiver_id bigint, user_sender_id bigint, primary key (id)) engine=InnoDB;
create table friendship_status (id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table likes (id bigint not null auto_increment, user_id bigint, user_post_id bigint, primary key (id)) engine=InnoDB;
create table movie (id integer not null, director varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table skills (id bigint not null auto_increment, tag_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, company_name varchar(255), description varchar(255), finished_at_month varchar(255), finished_at_year varchar(255), first_name varchar(255), last_name varchar(255), started_at_month varchar(255), started_at_year varchar(255), last_title varchar(255), username varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table userpost (id bigint not null auto_increment, content varchar(255), created_date datetime(6), file varchar(255), media varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, avatar varchar(255), email varchar(255) not null, email_verified bit not null, is_active bit, image_url varchar(255), is_company bit, name varchar(255) not null, password varchar(255), provider varchar(255) not null, provider_id varchar(255), username varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK9551piq2wp9kh4kket0wr65vt unique (username);
alter table user_profile add constraint UK_ebc21hy5j7scdvcjt0jy6xxrv unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_m6rqhr1nq3b6j8aglc4tlhaj6 unique (user_profile_id);
alter table friendship add constraint FKl3fmi2qvg60ic6kfaatp5fbci foreign key (user_receiver_id) references users (id);
alter table friendship add constraint FKgb2wm94b4p97ir8ghl18raqfs foreign key (user_sender_id) references users (id);
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users (id);
alter table likes add constraint FKqdo6v41e0f5uv4opn66n61wbe foreign key (user_post_id) references userpost (id);
alter table skills add constraint FK5fl0vpj28i7audg87u2322vn5 foreign key (tag_id) references tag (id);
alter table skills add constraint FKo8dhr4cqp5nowj5o9km5fjhaq foreign key (user_id) references users (id);
alter table user_profile add constraint FKuganfwvnbll4kn2a3jeyxtyi foreign key (user_id) references users (id);
alter table userpost add constraint FKnjhvkcvrsm7vksyjb7eljn2uw foreign key (user_profile_id) references user_profile (id);
alter table users add constraint FKgvxffhxghiogrd4g2sqompabh foreign key (user_profile_id) references user_profile (id);
create table friendship (id bigint not null auto_increment, status varchar(20), user_receiver_id bigint, user_sender_id bigint, primary key (id)) engine=InnoDB;
create table friendship_status (id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table likes (id bigint not null auto_increment, user_id bigint, user_post_id bigint, primary key (id)) engine=InnoDB;
create table movie (id integer not null, director varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table skills (id bigint not null auto_increment, tag_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, company_name varchar(255), description varchar(255), finished_at_month varchar(255), finished_at_year varchar(255), first_name varchar(255), last_name varchar(255), started_at_month varchar(255), started_at_year varchar(255), last_title varchar(255), username varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table userpost (id bigint not null auto_increment, content varchar(255), created_date datetime(6), file varchar(255), media varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, avatar varchar(255), email varchar(255) not null, email_verified bit not null, is_active bit, image_url varchar(255), is_company bit, name varchar(255) not null, password varchar(255), provider varchar(255) not null, provider_id varchar(255), username varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK9551piq2wp9kh4kket0wr65vt unique (username);
alter table user_profile add constraint UK_ebc21hy5j7scdvcjt0jy6xxrv unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_m6rqhr1nq3b6j8aglc4tlhaj6 unique (user_profile_id);
alter table friendship add constraint FKl3fmi2qvg60ic6kfaatp5fbci foreign key (user_receiver_id) references users (id);
alter table friendship add constraint FKgb2wm94b4p97ir8ghl18raqfs foreign key (user_sender_id) references users (id);
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users (id);
alter table likes add constraint FKqdo6v41e0f5uv4opn66n61wbe foreign key (user_post_id) references userpost (id);
alter table skills add constraint FK5fl0vpj28i7audg87u2322vn5 foreign key (tag_id) references tag (id);
alter table skills add constraint FKo8dhr4cqp5nowj5o9km5fjhaq foreign key (user_id) references users (id);
alter table user_profile add constraint FKuganfwvnbll4kn2a3jeyxtyi foreign key (user_id) references users (id);
alter table userpost add constraint FKnjhvkcvrsm7vksyjb7eljn2uw foreign key (user_profile_id) references user_profile (id);
alter table users add constraint FKgvxffhxghiogrd4g2sqompabh foreign key (user_profile_id) references user_profile (id);
create table friendship (id bigint not null auto_increment, status varchar(20), user_receiver_id bigint, user_sender_id bigint, primary key (id)) engine=InnoDB;
create table friendship_status (id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table likes (id bigint not null auto_increment, user_id bigint, user_post_id bigint, primary key (id)) engine=InnoDB;
create table movie (id integer not null, director varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table skills (id bigint not null auto_increment, tag_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, company_name varchar(255), description varchar(255), finished_at_month varchar(255), finished_at_year varchar(255), first_name varchar(255), last_name varchar(255), started_at_month varchar(255), started_at_year varchar(255), last_title varchar(255), username varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table userpost (id bigint not null auto_increment, content varchar(255), created_date datetime(6), file varchar(255), media varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, avatar varchar(255), email varchar(255) not null, email_verified bit not null, is_active bit, image_url varchar(255), is_company bit, name varchar(255) not null, password varchar(255), provider varchar(255) not null, provider_id varchar(255), username varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK9551piq2wp9kh4kket0wr65vt unique (username);
alter table user_profile add constraint UK_ebc21hy5j7scdvcjt0jy6xxrv unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_m6rqhr1nq3b6j8aglc4tlhaj6 unique (user_profile_id);
alter table friendship add constraint FKl3fmi2qvg60ic6kfaatp5fbci foreign key (user_receiver_id) references users (id);
alter table friendship add constraint FKgb2wm94b4p97ir8ghl18raqfs foreign key (user_sender_id) references users (id);
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users (id);
alter table likes add constraint FKqdo6v41e0f5uv4opn66n61wbe foreign key (user_post_id) references userpost (id);
alter table skills add constraint FK5fl0vpj28i7audg87u2322vn5 foreign key (tag_id) references tag (id);
alter table skills add constraint FKo8dhr4cqp5nowj5o9km5fjhaq foreign key (user_id) references users (id);
alter table user_profile add constraint FKuganfwvnbll4kn2a3jeyxtyi foreign key (user_id) references users (id);
alter table userpost add constraint FKnjhvkcvrsm7vksyjb7eljn2uw foreign key (user_profile_id) references user_profile (id);
alter table users add constraint FKgvxffhxghiogrd4g2sqompabh foreign key (user_profile_id) references user_profile (id);
create table friendship (id bigint not null auto_increment, status varchar(20), user_receiver_id bigint, user_sender_id bigint, primary key (id)) engine=InnoDB;
create table friendship_status (id bigint not null, status varchar(255), primary key (id)) engine=InnoDB;
create table likes (id bigint not null auto_increment, user_id bigint, user_post_id bigint, primary key (id)) engine=InnoDB;
create table movie (id integer not null, director varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table skills (id bigint not null auto_increment, tag_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table tag (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table user_profile (id bigint not null auto_increment, company_name varchar(255), description varchar(255), finished_at_month varchar(255), finished_at_year varchar(255), first_name varchar(255), last_name varchar(255), started_at_month varchar(255), started_at_year varchar(255), last_title varchar(255), username varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table userpost (id bigint not null auto_increment, content varchar(255), created_date datetime(6), file varchar(255), media varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, avatar varchar(255), email varchar(255) not null, email_verified bit not null, is_active bit, image_url varchar(255), is_company bit, name varchar(255) not null, password varchar(255), provider varchar(255) not null, provider_id varchar(255), username varchar(255), user_profile_id bigint, primary key (id)) engine=InnoDB;
alter table user_profile add constraint UK9551piq2wp9kh4kket0wr65vt unique (username);
alter table user_profile add constraint UK_ebc21hy5j7scdvcjt0jy6xxrv unique (user_id);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_m6rqhr1nq3b6j8aglc4tlhaj6 unique (user_profile_id);
alter table friendship add constraint FKl3fmi2qvg60ic6kfaatp5fbci foreign key (user_receiver_id) references users (id);
alter table friendship add constraint FKgb2wm94b4p97ir8ghl18raqfs foreign key (user_sender_id) references users (id);
alter table likes add constraint FKnvx9seeqqyy71bij291pwiwrg foreign key (user_id) references users (id);
alter table likes add constraint FKqdo6v41e0f5uv4opn66n61wbe foreign key (user_post_id) references userpost (id);
alter table skills add constraint FK5fl0vpj28i7audg87u2322vn5 foreign key (tag_id) references tag (id);
alter table skills add constraint FKo8dhr4cqp5nowj5o9km5fjhaq foreign key (user_id) references users (id);
alter table user_profile add constraint FKuganfwvnbll4kn2a3jeyxtyi foreign key (user_id) references users (id);
alter table userpost add constraint FKnjhvkcvrsm7vksyjb7eljn2uw foreign key (user_profile_id) references user_profile (id);
alter table users add constraint FKgvxffhxghiogrd4g2sqompabh foreign key (user_profile_id) references user_profile (id);
